<template>
  <v-card variant="text" class="mx-auto rounded-lg">
    <v-container fluid align="center">
      <v-col :cols="12" align="start" justify="start">
        <v-row dens align="start" justify="start">
          <v-card-title>{{
            options_SessionTypeAlternate[this.user_config.session_typeAlternate]
          }}</v-card-title>
        </v-row>
        <v-row dens align="start" justify="start">
          <MeditationPlayer
            :playerdata="task_data[this.user_config.session_typeAlternate]"
          />
        </v-row>
      </v-col>
    </v-container>
  </v-card>
</template>

<script>
import MeditationPlayer from "@/components/meditationPlayer.vue";

export default {
  name: "DebugMeditationView",
  data: () => ({
    // id of task
    // type of task (0 = intro, 1 = audio, 2 = interact, 3 = outro)
    // only if type is audio
    // only if type is interact
    // pause after
    options_SessionTypeAlternate: [
      "Lupenübung Stein (ca. 9 Minuten)",
      "Lupenübung Stock (ca. 9 Minuten)",
      "Lupenübung Statue (ca. 9 Minuten)",
      "Telefonübung Stein (ca. 6 Minuten)",
      "Telefonübung Stock (ca. 6 Minuten)",
      "Telefonübung Statue (ca. 7 Minuten)",
      "Imaginationsübung Stein (ca. 7 Minuten)",
      "Imaginationsübung Stock (ca. 7 Minuten)",
      "Imaginationsübung Statue (ca. 7 Minuten)",
    ],
    task_data: [
      // --------------------------------
      // 1. Lupenübung Stein (ca. 9 Minuten)
      // --------------------------------
      [
        {
          id: 0,
          type: 0,
          text: "Einleitung 1.1.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 1.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 1,
          type: 0,
          text: "Einleitung 2.1.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 2.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 2,
          type: 1,
          text: "Einleitung 2.2.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 2.2.wav",
          model: "",
          pause: 10,
        },
        {
          id: 3,
          type: 2,
          text: "Object Meditations/1/1.1.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/1/1.1.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 4,
          type: 2,
          text: "Object Meditations/1/1.2.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/1/1.2.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 4,
          type: 2,
          text: "Object Meditations/1/1.3.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/1/1.3.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 5,
          type: 2,
          text: "Object Meditations/1/1.4.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/1/1.4.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 6,
          type: 2,
          text: "Object Meditations/1/1.5.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/1/1.5.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 7,
          type: 2,
          text: "Object Meditations/1/1.6.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/1/1.6.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 8,
          type: 2,
          text: "Object Meditations/1/1.7.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/1/1.7.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 9,
          type: 2,
          text: "Object Meditations/1/1.8.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/1/1.8.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 10,
          type: 2,
          text: "Object Meditations/1/1.9.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/1/1.9.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 11,
          type: 2,
          text: "Object Meditations/1/1.10.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/1/1.10.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 12,
          type: 2,
          text: "Object Meditations/1/1.11.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/1/1.11.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 13,
          type: 2,
          text: "Object Meditations/1/1.12.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/1/1.12.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 14,
          type: 3,
          text: "Abschluss 1.1.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 15,
          type: 3,
          text: "Abschluss 1.2.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.2.wav",
          model: "",
          pause: 10,
        },
        {
          id: 16,
          type: 3,
          text: "Abschluss 1.3.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.3.wav",
          model: "",
          pause: 10,
        },
        {
          id: 17,
          type: 3,
          text: "Abschluss 1.4.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.4.wav",
          model: "",
          pause: 10,
        },
        {
          id: 18,
          type: 3,
          text: "Abschluss 1.5.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.5.wav",
          model: "",
          pause: 10,
        },
        {
          id: 19,
          type: 3,
          text: "End1.1",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/1/End1.1.wav",
          model: "",
          pause: 10,
        },
      ],
      // --------------------------------
      // 2. Lupenübung Stock (ca. 9 Minuten)
      // --------------------------------
      [
        {
          id: 0,
          type: 0,
          text: "Einleitung 1.2.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 1.2.wav",
          model: "",
          pause: 10,
        },
        {
          id: 1,
          type: 0,
          text: "Einleitung 2.1.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 2.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 2,
          type: 1,
          text: "Einleitung 2.3.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 2.3.wav",
          model: "",
          pause: 10,
        },
        {
          id: 3,
          type: 2,
          text: "Object Meditations/2/2.1.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/2/2.1.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 4,
          type: 2,
          text: "Object Meditations/2/2.2.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/2/2.2.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 5,
          type: 2,
          text: "Object Meditations/2/2.3.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/2/2.3.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 6,
          type: 2,
          text: "Object Meditations/2/2.4.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/2/2.4.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 7,
          type: 2,
          text: "Object Meditations/2/2.5.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/2/2.5.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 8,
          type: 2,
          text: "Object Meditations/2/2.6.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/2/2.6.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 9,
          type: 2,
          text: "Object Meditations/2/2.7.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/2/2.7.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 10,
          type: 2,
          text: "Object Meditations/2/2.8.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/2/2.8.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 11,
          type: 2,
          text: "Object Meditations/2/2.9.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/2/2.9.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 12,
          type: 2,
          text: "Object Meditations/2/2.10.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/2/2.10.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 13,
          type: 2,
          text: "Object Meditations/2/2.11.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/2/2.11.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 14,
          type: 3,
          text: "Abschluss 2.1.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 2.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 15,
          type: 3,
          text: "Abschluss 1.2.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.2.wav",
          model: "",
          pause: 10,
        },
        {
          id: 16,
          type: 3,
          text: "Abschluss 1.3.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.3.wav",
          model: "",
          pause: 10,
        },
        {
          id: 17,
          type: 3,
          text: "Abschluss 1.4.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.4.wav",
          model: "",
          pause: 10,
        },
        {
          id: 18,
          type: 3,
          text: "Abschluss 2.5.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 2.5.wav",
          model: "",
          pause: 10,
        },
      ],
      // ---------------------------------
      // 3. Lupenübung Statue (ca. 9 Minuten)
      // ---------------------------------
      [
        {
          id: 0,
          type: 0,
          text: "Einleitung 1.1.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 1.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 1,
          type: 0,
          text: "Einleitung 2.1.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 2.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 2,
          type: 1,
          text: "Einleitung 2.4.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 2.4.wav",
          model: "",
          pause: 10,
        },
        {
          id: 3,
          type: 2,
          text: "Object Meditations/3/3.1.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/3/3.1.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 4,
          type: 2,
          text: "Object Meditations/3/3.2.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/3/3.2.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 5,
          type: 2,
          text: "Object Meditations/3/3.3.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/3/3.3.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 6,
          type: 2,
          text: "Object Meditations/3/3.4.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/3/3.4.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 7,
          type: 2,
          text: "Object Meditations/3/3.5.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/3/3.5.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 8,
          type: 2,
          text: "Object Meditations/3/3.6.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/3/3.6.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 9,
          type: 2,
          text: "Object Meditations/3/3.7.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/3/3.7.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 10,
          type: 2,
          text: "Object Meditations/3/3.8.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/3/3.8.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 11,
          type: 2,
          text: "Object Meditations/3/3.9.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/3/3.9.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 14,
          type: 3,
          text: "Abschluss 1.1.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 16,
          type: 3,
          text: "Abschluss 1.3.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.3.wav",
          model: "",
          pause: 10,
        },
        {
          id: 17,
          type: 3,
          text: "Abschluss 1.4.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.4.wav",
          model: "",
          pause: 10,
        },
        {
          id: 18,
          type: 3,
          text: "Abschluss 1.5.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.5.wav",
          model: "",
          pause: 10,
        },
      ],
      // ---------------------------------
      // 4. Telefonübung Stein (ca. 6 Minuten)
      // ---------------------------------
      [
        {
          id: 0,
          type: 0,
          text: "Einleitung 1.1.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 1.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 1,
          type: 0,
          text: "Einleitung 3.1.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 3.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 2,
          type: 0,
          text: "Einleitung 2.2.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 2.2.wav",
          model: "",
          pause: 10,
        },
        {
          id: 3,
          type: 2,
          text: "Object Meditations/4/4.4.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/4/4.4.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 4,
          type: 2,
          text: "Object Meditations/4/4.5.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/4/4.5.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 5,
          type: 2,
          text: "Object Meditations/4/4.5a.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/4/4.5a.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 6,
          type: 2,
          text: "Object Meditations/4/4.6.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/4/4.6.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 7,
          type: 2,
          text: "Object Meditations/4/4.7.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/4/4.7.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 8,
          type: 2,
          text: "Object Meditations/4/4.8.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/4/4.8.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 9,
          type: 2,
          text: "Object Meditations/4/4.9.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/4/4.9.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 10,
          type: 2,
          text: "Object Meditations/4/4.10.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/4/4.10.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 11,
          type: 2,
          text: "Object Meditations/4/4.11.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/4/4.11.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 12,
          type: 2,
          text: "Object Meditations/4/4.12.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/4/4.12.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 13,
          type: 3,
          text: "Abschluss 1.1.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 14,
          type: 3,
          text: "Abschluss 1.3.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.3.wav",
          model: "",
          pause: 10,
        },
        {
          id: 15,
          type: 3,
          text: "Abschluss 1.4.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.4.wav",
          model: "",
          pause: 10,
        },
        {
          id: 16,
          type: 3,
          text: "Abschluss 1.5.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.5.wav",
          model: "",
          pause: 10,
        },
      ],
      //-----------------------------------
      // 5. Telefonübung Stock (ca. 6 Minuten)
      //-----------------------------------
      [
        {
          id: 0,
          type: 0,
          text: "Einleitung 1.1.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 1.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 1,
          type: 0,
          text: "Einleitung 3.1.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 3.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 2,
          type: 0,
          text: "Einleitung 2.2.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 2.2.wav",
          model: "",
          pause: 10,
        },
        {
          id: 3,
          type: 2,
          text: "Object Meditations/5/5.4.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/5/5.4.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 4,
          type: 2,
          text: "Object Meditations/5/5.5.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/5/5.5.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 5,
          type: 2,
          text: "Object Meditations/5/5.5a.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/5/5.5a.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 6,
          type: 2,
          text: "Object Meditations/5/5.6.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/5/5.6.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 7,
          type: 2,
          text: "Object Meditations/5/5.7.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/5/5.7.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 8,
          type: 2,
          text: "Object Meditations/5/5.8.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/5/5.8.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 9,
          type: 2,
          text: "Object Meditations/5/5.9.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/5/5.9.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 10,
          type: 2,
          text: "Object Meditations/5/5.10.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/5/5.10.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 11,
          type: 2,
          text: "Object Meditations/5/5.11.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/5/5.11.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 12,
          type: 2,
          text: "Object Meditations/5/5.12.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/5/5.12.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 13,
          type: 3,
          text: "Abschluss 1.1.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 14,
          type: 3,
          text: "Abschluss 1.3.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.3.wav",
          model: "",
          pause: 10,
        },
        {
          id: 15,
          type: 3,
          text: "Abschluss 1.4.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.4.wav",
          model: "",
          pause: 10,
        },
        {
          id: 16,
          type: 3,
          text: "Abschluss 1.5.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.5.wav",
          model: "",
          pause: 10,
        },
      ],
      //-----------------------------------
      // 6. Telefonübung Statue (ca. 7 Minuten)
      //-----------------------------------
      [
        {
          id: 0,
          type: 0,
          text: "Einleitung 1.1.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 1.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 1,
          type: 0,
          text: "Einleitung 3.1.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 3.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 2,
          type: 0,
          text: "Einleitung 2.2.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 2.2.wav",
          model: "",
          pause: 10,
        },
        {
          id: 3,
          type: 2,
          text: "Object Meditations/6/6.4.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/6/6.4.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 4,
          type: 2,
          text: "Object Meditations/6/6.5.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/6/6.5.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 5,
          type: 2,
          text: "Object Meditations/6/6.5a.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/6/6.5a.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 6,
          type: 2,
          text: "Object Meditations/6/6.6.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/6/6.6.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 7,
          type: 2,
          text: "Object Meditations/6/6.7.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/6/6.7.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 8,
          type: 2,
          text: "Object Meditations/6/6.8.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/6/6.8.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 9,
          type: 2,
          text: "Object Meditations/6/6.9.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/6/6.9.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 10,
          type: 2,
          text: "Object Meditations/6/6.10.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/6/6.10.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 11,
          type: 2,
          text: "Object Meditations/6/6.11.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/6/6.11.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 12,
          type: 2,
          text: "Object Meditations/6/6.12.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/6/6.12.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 13,
          type: 3,
          text: "Abschluss 1.1.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 14,
          type: 3,
          text: "Abschluss 1.3.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.3.wav",
          model: "",
          pause: 10,
        },
        {
          id: 15,
          type: 3,
          text: "Abschluss 1.4.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.4.wav",
          model: "",
          pause: 10,
        },
        {
          id: 16,
          type: 3,
          text: "Abschluss 1.5.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.5.wav",
          model: "",
          pause: 10,
        },
      ],
      //-----------------------------------
      // 7. Imaginationsübung Stein (ca. 7 Minuten)
      //-----------------------------------
      [
        {
          id: 0,
          type: 0,
          text: "Einleitung 1.1.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 1.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 1,
          type: 0,
          text: "Einleitung 4.1.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 4.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 2,
          type: 0,
          text: "Einleitung 2.2.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 2.2.wav",
          model: "",
          pause: 10,
        },
        {
          id: 3,
          type: 2,
          text: "Object Meditations/7/7.4.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/7/7.4.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 4,
          type: 2,
          text: "Object Meditations/7/7.5.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/7/7.5.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 5,
          type: 2,
          text: "Object Meditations/7/7.6.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/7/7.6.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 6,
          type: 2,
          text: "Object Meditations/7/7.7.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/7/7.7.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 7,
          type: 2,
          text: "Object Meditations/7/7.8.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/7/7.8.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 8,
          type: 2,
          text: "Object Meditations/7/7.9.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/7/7.9.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 9,
          type: 2,
          text: "Object Meditations/7/7.10.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/7/7.10.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 10,
          type: 2,
          text: "Object Meditations/7/7.11.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/7/7.11.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 11,
          type: 2,
          text: "Object Meditations/7/7.12.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/7/7.12.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 12,
          type: 2,
          text: "Object Meditations/7/7.13.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/7/7.13.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 13,
          type: 3,
          text: "Abschluss 1.1.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 14,
          type: 3,
          text: "Abschluss 1.3.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.3.wav",
          model: "",
          pause: 10,
        },
        {
          id: 15,
          type: 3,
          text: "Abschluss 1.4.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.4.wav",
          model: "",
          pause: 10,
        },
        {
          id: 16,
          type: 3,
          text: "Abschluss 1.5.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.5.wav",
          model: "",
          pause: 10,
        },
      ],
      //-----------------------------------
      // 8. Imaginationsübung Stock (ca. 7 Minuten)
      //-----------------------------------
      [
        {
          id: 0,
          type: 0,
          text: "Einleitung 1.1.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 1.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 1,
          type: 0,
          text: "Einleitung 4.1.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 4.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 2,
          type: 0,
          text: "Einleitung 2.2.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 2.2.wav",
          model: "",
          pause: 10,
        },
        {
          id: 3,
          type: 2,
          text: "Object Meditations/8/8.4.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/8/8.4.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 4,
          type: 2,
          text: "Object Meditations/8/8.5.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/8/8.5.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 5,
          type: 2,
          text: "Object Meditations/8/8.6.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/8/8.6.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 6,
          type: 2,
          text: "Object Meditations/8/8.7.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/8/8.7.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 7,
          type: 2,
          text: "Object Meditations/8/8.8.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/8/8.8.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 8,
          type: 2,
          text: "Object Meditations/8/8.9.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/8/8.9.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 9,
          type: 2,
          text: "Object Meditations/8/8.10.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/8/8.10.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 10,
          type: 2,
          text: "Object Meditations/8/8.11.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/8/8.11.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 11,
          type: 2,
          text: "Object Meditations/8/8.12.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/8/8.12.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 12,
          type: 2,
          text: "Object Meditations/8/8.13.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/8/8.13.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 13,
          type: 2,
          text: "Object Meditations/8/8.14.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/8/8.14.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 14,
          type: 2,
          text: "Object Meditations/8/8.15.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/8/8.15.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 15,
          type: 3,
          text: "Abschluss 1.1.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 16,
          type: 3,
          text: "Abschluss 1.3.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.3.wav",
          model: "",
          pause: 10,
        },
        {
          id: 17,
          type: 3,
          text: "Abschluss 1.4.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.4.wav",
          model: "",
          pause: 10,
        },
        {
          id: 18,
          type: 3,
          text: "Abschluss 1.5.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.5.wav",
          model: "",
          pause: 10,
        },
      ],
      //-----------------------------------
      // 9. Imaginationsübung Statue (ca. 7 Minuten)
      //-----------------------------------
      [
        {
          id: 0,
          type: 0,
          text: "Einleitung 1.1.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 1.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 1,
          type: 0,
          text: "Einleitung 4.1.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 4.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 2,
          type: 0,
          text: "Einleitung 2.2.wav",
          audio: "/MindfulnessExercises/Intros/Einleitung 2.2.wav",
          model: "",
          pause: 10,
        },
        {
          id: 3,
          type: 2,
          text: "Object Meditations/9/9.4.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/9/9.4.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 4,
          type: 2,
          text: "Object Meditations/9/9.5.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/9/9.5.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 5,
          type: 2,
          text: "Object Meditations/9/9.6.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/9/9.6.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 6,
          type: 2,
          text: "Object Meditations/9/9.7.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/9/9.7.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 7,
          type: 2,
          text: "Object Meditations/9/9.8.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/9/9.8.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 8,
          type: 2,
          text: "Object Meditations/9/9.9.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/9/9.9.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 9,
          type: 2,
          text: "Object Meditations/9/9.10.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/9/9.10.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 10,
          type: 2,
          text: "Object Meditations/9/9.11.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/9/9.11.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 11,
          type: 2,
          text: "Object Meditations/9/9.12.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/9/9.12.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 12,
          type: 2,
          text: "Object Meditations/9/9.13.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/9/9.13.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 13,
          type: 2,
          text: "Object Meditations/9/9.14.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/9/9.14.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 14,
          type: 2,
          text: "Object Meditations/9/9.15.wav",
          audio: "/MindfulnessExercises/Meditations/Object Meditations/9/9.15.wav",
          model: "Rock1b.obj",
          pause: 10,
        },
        {
          id: 15,
          type: 3,
          text: "Abschluss 1.1.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.1.wav",
          model: "",
          pause: 10,
        },
        {
          id: 16,
          type: 3,
          text: "Abschluss 1.3.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.3.wav",
          model: "",
          pause: 10,
        },
        {
          id: 17,
          type: 3,
          text: "Abschluss 1.4.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.4.wav",
          model: "",
          pause: 10,
        },
        {
          id: 18,
          type: 3,
          text: "Abschluss 1.5.wav",
          audio: "/MindfulnessExercises/Outtros/Abschluss 1.5.wav",
          model: "",
          pause: 10,
        },
      ],
    ],
  }),
  props: ["user_config", "onBack", "onNext"],
  components: { MeditationPlayer },
  mounted: function () {
    //alert(this.user_config.session_typeAlternate);
  },
  methods: {},
};
</script>

<style></style>
